### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by iyeldinov** [andrewdacenko/ng-validator#1]
- [x] to write a documentation
- [x] create github page

**Comment by andrewdacenko** [comment]
Thanks. Working over it

**Comment by andrewdacenko** [comment]
67ac5979058f9d6860bc67f6dac702ca7f471c63 Minimal doc

**Comment by andrewdacenko** [comment]
starting github page done [http://andrewdacenko.github.io/ng-validator/](http://andrewdacenko.github.io/ng-validator/)
